site_name: Web Development
theme:
    name: material

nav:
  - Home: index.md
  - XAMPP: xampp.md

repo_name: mapattacker/web-development
repo_url: https://github.com/mapattacker/web-development

markdown_extensions:
    - admonition
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg